### ISSUE TITLE
Domain & Hosting

### ISSUE THREAD

**Issue by RobHowdle** [Droid-Builder-Web-Team/ChecklistApp#11]
Final domain and hosting needs to be sorted and agreed upon. Not urgent right now.

**Comment by dpoulson** [comment]
Just my thoughts (mentioned in chat the other day)

Should be able to host on the same hosting as their wiki? That leaves checklist.droidbuilders.net as a possibility for the more generic checklist app.

**Comment by RobHowdle** [comment]
Michael and Darren discussed hosting and went with the RCH Hosting. Once this is set up we can upload the countdown timer to the hosting, update the links and make that live.
