### ISSUE TITLE
Check 'droid_section' on all droids

### ISSUE THREAD

**Issue by circuitBurn** [Droid-Builder-Web-Team/ChecklistApp#137]
Some droids (Chopper) don't have proper 'droid_section' separation. Chopper only has 'Chopper' in the droid_section column. Needs separation into Dome, Legs, etc...

**Comment by RobHowdle** [comment]
I'll take a look at the CSV tonight and see if there is something in the wrong place. Chopper should be split up into sections already but if the CSV hasn't formatted it correctly then it wont register the sections.
