### ISSUE TITLE
Complete vs N/A should be radio button

### ISSUE THREAD

**Issue by ridilen** [Droid-Builder-Web-Team/ChecklistApp#158]
You can select both complete and radio buttons which can affect your total printed parts.  Could this be made radio buttons to alleviate this.

![image](https://user-images.githubusercontent.com/57424927/96054802-7ea75480-0e50-11eb-9551-8956964edce8.png)

**Comment by RobHowdle** [comment]
Issue added for bug fixing. Thank you.

**Comment by RobHowdle** [comment]
Latest version has the ability to select N/A and the completed section is then disabled. Users can still selected completed AND N/A encase the user has misprinted a part they are no longer using but still wants to keep track of them. #162 

Now closing issue as resolved.
