### ISSUE TITLE
Custom droid may want to include photo from selector

### ISSUE THREAD

**Issue by ridilen** [Droid-Builder-Web-Team/ChecklistApp#159]
When you build a custom droid the photo shown is the wrench and pencil.  Would be nice to have the photo reflect the selections you picked.

![image](https://user-images.githubusercontent.com/57424927/96055603-80721780-0e52-11eb-8020-8a281162af65.png)

**Comment by RobHowdle** [comment]
This is something we are looking at implimenting in a way however it is not something that will be ready for the launch sadly.

**Comment by circuitBurn** [comment]
I've just added a feature to allow users to add their own images in the droid details.

![image](https://user-images.githubusercontent.com/4070810/97065964-34745080-157f-11eb-91f1-88fbb0e04dbf.JPG)
