### ISSUE TITLE
Droid name not reflected from description

### ISSUE THREAD

**Issue by ridilen** [Droid-Builder-Web-Team/ChecklistApp#160]
Would be nice to have the name on My Droids use the name that you enter under Droid Designation. Creating a droid and having shown as Custom on everything will be confusing.

![image](https://user-images.githubusercontent.com/57424927/96055821-1443e380-0e53-11eb-8008-ee33ca07475c.png)

![image](https://user-images.githubusercontent.com/57424927/96055836-1c038800-0e53-11eb-8d66-8f00aa3f5c0d.png)

**Comment by RobHowdle** [comment]
Added to the bug list.

**Comment by RobHowdle** [comment]
Bug now fixed in #165
