### ISSUE TITLE
Image Upload Error from Mobile Devices

### ISSUE THREAD

**Issue by RobHowdle** [Droid-Builder-Web-Team/ChecklistApp#175]
When I was attempting to upload either a profile picture directly from a mobile device or upload a droid image, I was receiving success messages however once I would refresh or go to view the image, nothing was there. No errors were given.

Attemping on a desktop, the profile picture uploader gives the same success message however no image uploads and when you refresh the page and check the console there is a 404 error for the profile picture with the URL to the image however it doesn't seem to be able to find that image. The Droid Image Upload works on Desktop but doesn't work on mobile.

**Comment by circuitBurn** [comment]
Issue was missing symlink between storage and public storage. Issue resolved once created.
