### ISSUE TITLE
Popup window is annoying when clicking on the parts checklist

### ISSUE THREAD

**Issue by dpoulson** [Droid-Builder-Web-Team/ChecklistApp#55]
Not sure if that was just in as debug, so possibly it can be removed.

Tho a nice div style alert might be nice, that just pops up in a corner as visual feedback and disappears after a few seconds.

**Comment by RobHowdle** [comment]
@patrickatkeylogic @circuitBurn - Can you take a look at this when you do the "confirm with user before delete" button please? I believe @TemporalCoder started this when he was doing to database update on click but I don't think this part was removed once testing was complete.

**Comment by circuitBurn** [comment]
Sure thing. What's this popup doing and what is it supposed to do?

**Comment by RobHowdle** [comment]
@circuitBurn Screenshots attached. Currently you get an alert everytime you tick/ untick a box. I believe this was done to test it works but was never finished as in stopping it popping up. I'm not sure the best way to alert the user that it's been saved as it's an ajax request so on click the DB is updated (the submit button needs removing now and testing to make sure everything still works). Not sure if something like what was done on the profile page when you add an avatar and it gives that notification?


![Snip1](https://user-images.githubusercontent.com/43747640/91863736-57614300-ec67-11ea-8c2d-99106fd0ed9b.PNG)
![Snip2](https://user-images.githubusercontent.com/43747640/91863739-57f9d980-ec67-11ea-8dca-dea83febb1d2.PNG)
