### ISSUE TITLE
Can't delete a user

### ISSUE THREAD

**Issue by dpoulson** [Droid-Builder-Web-Team/ChecklistApp#58]
Subject says it all, the delete button on the user admin screen gives back an error.

**Comment by RobHowdle** [comment]
This (I hope) will be resolved once the admin panel is working. Currently have datatable probems with the links so they're not working yet.

**Comment by dpoulson** [comment]
Seems its a case of the standard user seed doesn't have a matching profile, so causing a null error. Think this is just a case of a duff user, so shouldn't be an issue going forward.
