### ISSUE TITLE
Multiple of the same droids doesn't show checklist

### ISSUE THREAD

**Issue by RobHowdle** [Droid-Builder-Web-Team/ChecklistApp#70]
Testing multiple of the same droids shows that when the user has one Droid for example Chopper, the checklist appears perfectly fine however if the user has a second chopper, the checklist doesn't load.

The fact builders often have multiple droids usually the same could mean this will be a problem.

**Comment by dpoulson** [comment]
Fixed with latest commit: 105da74c25d2149baa5be1ee159b0e8366e460f3

Was pulling back multiple rows, but only using the first entry. So reversed the sort order.

Not the best solution, but it works until things get rewritten with eloquent.
