### ISSUE TITLE
Update Archives Button

### ISSUE THREAD

**Issue by RobHowdle** [Droid-Builder-Web-Team/ChecklistApp#89]
Need advice on how to handle this, Checklist uses AJAX, button feels clunkly and possibly not user friendly.

**Comment by circuitBurn** [comment]
Add auto-save feature to the droid details form.

- Save on input blur
- Save after 3-4 seconds of inactivity after an input change event
- Ensure input validation updates correctly on change
- Ensure input validation displays proper message for each input
- Ensure form is validated before saving
- Add toast to indicate successful save
